---
    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: bugoga/ngnx:latest
        ports:
        - containerPort: 443
          hostPort: 443
        - containerPort: 80
          hostPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30080
      name: htp
    - port: 443
      nodePort: 30081
      name: hts
  selector:
    name: nginx
        
---
    
apiVersion: v1
kind: Service
metadata:
  name: lb-nginx
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
    name: ngnx-htp
  - port: 443
    targetPort: 443
    name: ngnx-hts
  type: LoadBalancer
    
    