---

- hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Upgrade System
      apt:
        update_cache: yes

    - name: Install NGINX
      apt:
       name: nginx
       state: present

    - name: Add certbot repository
      apt_repository:
       repo: 'ppa:certbot/certbot'

    - name: Install Certbot's Nginx package
      apt:
       name: python-certbot-nginx
       state: present

    - name: Template NGINX conf gnerator
      vars:
        HOST_COUNT: "{{ groups['all'] | length }}"
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf

    - name: Template NGINX conf gnerator
      vars:
        HOST_COUNT: "{{ groups['all'] | length }}"
      template:
        src: default.j2
        dest: /etc/nginx/sites-available/default
