---

- hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Upgrade System
      apt:
        update_cache: yes

    - name: Install NGINX
      apt:
       name: nginx
       state: present

    - name: Add certbot repository
      apt_repository:
       repo: 'ppa:certbot/certbot'

    - name: Install Certbot's Nginx package
      apt:
       name: python-certbot-nginx
       state: present

    - name: cp
      copy:
        src: ansibloom/block1/foo
        dest: /home/ubuntu
