---

- hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Upgrade System
      apt:
        update_cache: yes

    - name: Install NGINX
      apt:
       name: nginx
       state: present

    - name: Add certbot repository
      apt_repository:
       repo: 'ppa:certbot/certbot'

    - name: Install Certbot's Nginx package
      apt:
       name: python-certbot-nginx
       state: present


    - name: show all the hosts matching the pattern, i.e. all but the group www
      debug:
       msg: "{{ item }}"
      with_inventory_hostnames:
       - all

    - name: temp
      template:
        src: nginx.conf.j2
        dest: /home/ubuntu/nginx.conf

    - name: Print some debug information
      vars:
       msg: |
        Module Variables ("vars"):
        --------------------------------
        {{ vars | to_nice_json }}

      

        GROUPS Variables ("groups"):
        --------------------------------
        {{ groups | to_nice_json }}



      debug:
       msg: "{{ msg.split('\n') }}"
      tags: debug_info
