---

- hosts: tag_Environment_Staging
  gather_facts: true
  serial: 1
  become: true

  tasks:
    - name: Add host
      add_host:
       hostname: back.bugoga.ga

    - name: Copy front
      synchronize: src=/var/www/front dest=/var/www
      delegate_to: back.bugoga.ga

    - name: Copy back
      synchronize:
        src: /opt/tomcat/latest/webapps
        dest: /opt/tomcat/latest
        rsync_path: "sudo rsync"
      delegate_to: back.bugoga.ga

    - name: Reload daemons
      service: name=nginx state=restarted
      service: name=tomcat state=restarted
