---

- hosts: all
  gather_facts: true
  become: true

  tasks:
    - name: Add host
      add_host:
       hostname: back.bugoga.ga
    - name: show the groups the host(s) are in
      debug:
       msg: "{{group_names}}"
