---

- hosts: tag_Environment_Staging
  gather_facts: true
  become: true

  tasks:
    - name: Add host
      add_host:
       hostname: back.bugoga.ga
    - name: Copy Remote-To-Remote
      synchronize: src=/var/www/front dest=/var/www/front
      delegate_to: back.bugoga.ga
