---

- name: Download telegraf package
  get_url:
    url: https://dl.influxdata.com/telegraf/releases/telegraf_1.13.2-1_amd64.deb

- name: Installing package     
  apt:
    deb: telegraf_1.13.2-1_amd64.deb

- name: Configuring filters
  shell: telegraf --input-filter cpu:mem:disk:diskio:kernel:system:nginx:tomcat:mysql --output-filter influxdb config > /etc/telegraf/telegraf.conf   

- name: Configuring destination output
  shell: sed -i 's/# urls = \[\"http:\/\/127.0.0.1:8086\"\]/urls = \[\"http:\/\/innodb.bugoga.ga:8086\"\]/g' /etc/telegraf/telegraf.conf

- name: Install venv
  apt: name=virtualenv

- name: Clone plugin repo
  git:
    repo: 'https://github.com/ratibor78/srvstatus.git'
    dest: /opt

- name: Install requirements
  pip: 
    requirements: requirements.txt
    virtualenv: venv
    virtualenv_python: python3
  args:
    chdir: /opt/srvstatus

 - name: virtualenv activate
      shell: source venv/bin/activate    
   args:
    chdir: /opt/srvstatus






- name: Install JAVA
  apt: name=default-jdk

- name: Install wget
  apt: name=wget

- name: Install unzip
  apt: name=unzip

- name: Add group "tomcat"
  group: name=tomcat

- name: Add user "tomcat"
  user: name=tomcat group=tomcat home=/opt/tomcat createhome=no
  become: True
  become_method: sudo

- name: Create tomcat directory
  file: name=/opt/tomcat state=directory

- name: Download Tomcat
  get_url:
    url: http://apache.ip-connect.vn.ua/tomcat/tomcat-9/v9.0.30/bin/apache-tomcat-9.0.30.tar.gz
    dest: /tmp

- name: Extract archive
  command: chdir=/opt/tomcat /bin/tar xvf /tmp/apache-tomcat-9.0.30.tar.gz -C /opt/tomcat/ creates=/opt/tomcat/apache-tomcat-9.0.30

- name: Symlink install directory
  file: src=/opt/tomcat/apache-tomcat-9.0.30 path=/opt/tomcat/latest state=link

- name: Change ownership of Tomcat installation
  file: path=/opt/tomcat/ owner=tomcat group=tomcat state=directory recurse=yes

- name: COnfiguring daemon
  shell: sh -c 'chmod +x /opt/tomcat/latest/bin/*.sh'

- name: Daemon linking
  copy: src=tomcat.service dest=/etc/systemd/system/

- name: Set roles
  copy: src=tomcat-users.xml dest=/opt/tomcat/latest/conf/

- name: Tystemd daemon-reload
  shell: systemctl daemon-reload

- name: Tomcat9 start enable
  service: name=tomcat state=started enabled=yes
