---

- name: Download telegraf package
  get_url:
    url: https://dl.influxdata.com/telegraf/releases/telegraf_1.13.2-1_amd64.deb
    dest: telegraf_1.13.2-1_amd64.deb

- name: Installing package     
  apt:
    deb: telegraf_1.13.2-1_amd64.deb

- name: Configuring filters
  shell: telegraf --input-filter cpu:mem:disk:diskio:kernel:system:nginx:tomcat:mysql --output-filter influxdb config > /etc/telegraf/telegraf.conf   

- name: Configuring destination output
  shell: sed -i 's/# urls = \[\"http:\/\/127.0.0.1:8086\"\]/urls = \[\"http:\/\/innodb.bugoga.ga:8086\"\]/g' /etc/telegraf/telegraf.conf

- name: Install venv
  apt: name=virtualenv

- name: Clone plugin repo
  git:
    repo: 'https://github.com/ratibor78/srvstatus.git'
    dest: /opt

- name: Install requirements
  pip: 
    requirements: requirements.txt
    virtualenv: venv
    virtualenv_python: python3
  args:
    chdir: /opt/srvstatus

- name: virtualenv activate
  shell: source venv/bin/activate    
  args:
   chdir: /opt/srvstatus
