version: '3'
services:
     
  nginx-server:
    image: nginx:latest
    networks:
      - consultation
    ports:
      - "80:80" 

  consul-agent-0: &consul-agent
    image: consul:latest
    networks:
      - consultation
    entrypoint: /bin/sh -c
    command: >
      "echo '{\"service\": {\"name\": \"nginx\", \"tags\": [\"web\"], \"port\": 80}}' >> /consul/config/web.json  
      && /usr/local/bin/docker-entrypoint.sh  agent -retry-join consul-server-bootstrap -client 0.0.0.0"
#  consul-agent-1:
#    <<: *consul-agent
  consul-server-1: &consul-server
    image: consul:latest
    networks:
      - consultation
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-server-2:
    <<: *consul-server

  consul-server-bootstrap:
    <<: *consul-server
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: "agent -server -bootstrap-expect 3 -ui -client 0.0.0.0"

networks:
  consultation:
